# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

module Rooq
  module Generator
    class CodeGenerator
      extend T::Sig

      sig { params(schema_info: T::Array[T.untyped], typed: T::Boolean, namespace: String).void }
      def initialize(schema_info, typed: true, namespace: "Schema")
        @schema_info = schema_info
        @typed = typed
        @namespace = namespace
      end

      sig { returns(String) }
      def generate
        tables_code = @schema_info.map { |table_info| generate_table(table_info) }

        if @typed
          generate_typed(tables_code)
        else
          generate_untyped(tables_code)
        end
      end

      private

      sig { params(tables_code: T::Array[String]).returns(String) }
      def generate_typed(tables_code)
        <<~RUBY
          # typed: strict
          # frozen_string_literal: true

          # Auto-generated by Rooq - DO NOT EDIT
          # Generated at: #{Time.now.utc.iso8601}

          require "rooq"
          require "sorbet-runtime"

          module #{@namespace}
            extend T::Sig

          #{indent(tables_code.join("\n\n"), 2)}
          end
        RUBY
      end

      sig { params(tables_code: T::Array[String]).returns(String) }
      def generate_untyped(tables_code)
        untyped_tables = tables_code.map { |code| code.gsub(/T\.let\((.*), Rooq::Table\)/, '\1') }

        <<~RUBY
          # frozen_string_literal: true

          # Auto-generated by Rooq - DO NOT EDIT
          # Generated at: #{Time.now.utc.iso8601}

          require "rooq"

          module #{@namespace}
          #{indent(untyped_tables.join("\n\n"), 2)}
          end
        RUBY
      end

      sig { params(table_info: T.untyped).returns(String) }
      def generate_table(table_info)
        const_name = table_info.name.to_s.upcase
        fields_code = table_info.columns.map do |column|
          "    t.field :#{column.name}, :#{column.type}"
        end.join("\n")

        <<~RUBY.chomp
          #{const_name} = T.let(Rooq::Table.new(:#{table_info.name}) do |t|
          #{fields_code}
          end, Rooq::Table)
        RUBY
      end

      private

      sig { params(text: String, spaces: Integer).returns(String) }
      def indent(text, spaces)
        text.lines.map { |line| "#{' ' * spaces}#{line}" }.join
      end
    end
  end
end
