# frozen_string_literal: true

module Rooq
  module Generator
    class CodeGenerator
      def initialize(schema_info)
        @schema_info = schema_info
      end

      def generate
        tables_code = @schema_info.map { |table_info| generate_table(table_info) }

        <<~RUBY
          # frozen_string_literal: true

          # Auto-generated by Rooq - DO NOT EDIT
          # Generated at: #{Time.now.utc.iso8601}

          require "rooq"

          module Schema
          #{indent(tables_code.join("\n\n"), 2)}
          end
        RUBY
      end

      def generate_table(table_info)
        class_name = camelize(table_info.name)
        fields_code = table_info.columns.map do |column|
          "    t.field :#{column.name}, :#{column.type}"
        end.join("\n")

        <<~RUBY.chomp
          #{class_name.upcase} = Rooq::Table.new(:#{table_info.name}) do |t|
          #{fields_code}
          end
        RUBY
      end

      private

      def camelize(string)
        string.to_s.split("_").map(&:capitalize).join
      end

      def indent(text, spaces)
        text.lines.map { |line| "#{' ' * spaces}#{line}" }.join
      end
    end
  end
end
