# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

module Rooq
  module Generator
    class CodeGenerator
      extend T::Sig

      sig { params(schema_info: T::Array[Introspector::TableInfo]).void }
      def initialize(schema_info)
        @schema_info = schema_info
      end

      sig { returns(String) }
      def generate
        tables_code = @schema_info.map { |table_info| generate_table(table_info) }

        <<~RUBY
          # typed: strict
          # frozen_string_literal: true

          # Auto-generated by Rooq - DO NOT EDIT
          # Generated at: #{Time.now.utc.iso8601}

          require "rooq"
          require "sorbet-runtime"

          module Schema
            extend T::Sig

          #{indent(tables_code.join("\n\n"), 2)}
          end
        RUBY
      end

      sig { params(table_info: Introspector::TableInfo).returns(String) }
      def generate_table(table_info)
        class_name = camelize(table_info.name)
        const_name = class_name.upcase
        fields_code = table_info.columns.map do |column|
          "    t.field :#{column.name}, :#{column.type}"
        end.join("\n")

        <<~RUBY.chomp
          #{const_name} = T.let(Rooq::Table.new(:#{table_info.name}) do |t|
          #{fields_code}
          end, Rooq::Table)
        RUBY
      end

      private

      sig { params(string: T.any(String, Symbol)).returns(String) }
      def camelize(string)
        string.to_s.split("_").map(&:capitalize).join
      end

      sig { params(text: String, spaces: Integer).returns(String) }
      def indent(text, spaces)
        text.lines.map { |line| "#{' ' * spaces}#{line}" }.join
      end
    end
  end
end
